server:
  port: 8081 #运行端口号
  servlet:
    context-path: /
spring:
  application:
    name: eureka-client1 #服务名称
eureka:
  instance:
    prefer-ip-address: true #将IP注册到eureka中，如果为false默认注册主机名
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://admin:csstsari@localhost:8180/eureka/ #配置注册中心地址
