server:
  servlet:
    context-path: /
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://tx2.luxiang.info:3306/springbootlearn
    username: root
    password: Csstsari107!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
logging:
  level:
    com.switchvov.swagger: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE