server:
  port: 8180 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
  security: #配置SpringSecurity登录用户名和密码
    user:
      name: admin
      password: csstsari
eureka:
  instance:
    prefer-ip-address: true #将IP注册到eureka中，如果为false默认注册主机名
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
    serviceUrl:
      defaultZone: http://admin:csstsari@localhost:8180/eureka/
  server:
    enable-self-preservation: false #关闭保护模式