server:
  port: 8080 #运行端口号
  servlet:
    context-path: /
spring:
  application:
    name: redis #服务名称
  redis:
    database: 0
    host: tx2.luxiang.info
    port: 6379
    password: csstsari
    timeout: 3000
    ################ Redis 线程池设置 ##############
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0